resource "aws_secretsmanager_secret" "db_auth_password" {
  name                    = "${var.project_name}/db/auth"
  recovery_window_in_days = 0    # immediate deletion for dev
}

resource "aws_secretsmanager_secret_version" "db_auth_password" {
  secret_id     = aws_secretsmanager_secret.db_auth_password.id
  secret_string = var.db_master_password_auth
}

resource "aws_secretsmanager_secret" "db_banking_password" {
  name                    = "${var.project_name}/db/banking"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "db_banking_password" {
  secret_id     = aws_secretsmanager_secret.db_banking_password.id
  secret_string = var.db_master_password_banking
}

# --- RSA private key for auth-service JWT signing ---
# Generated once locally and committed to tfvars, OR generated by Terraform on first apply.
# We'll do the former — generate locally, store in Secrets Manager.

resource "aws_secretsmanager_secret" "jwt_private_key" {
  name                    = "${var.project_name}/jwt/private-key"
  recovery_window_in_days = 0
}

# Read from a local file. Generate with: openssl genpkey -algorithm RSA \
#   -out keys/private_key.pem -pkeyopt rsa_keygen_bits:2048
resource "aws_secretsmanager_secret_version" "jwt_private_key" {
  secret_id     = aws_secretsmanager_secret.jwt_private_key.id
  secret_string = file("${path.module}/../keys/private_key.pem")
}

resource "aws_secretsmanager_secret" "jwt_public_key" {
  name                    = "${var.project_name}/jwt/public-key"
  recovery_window_in_days = 0
}

resource "aws_secretsmanager_secret_version" "jwt_public_key" {
  secret_id     = aws_secretsmanager_secret.jwt_public_key.id
  secret_string = file("${path.module}/../keys/public_key.pem")
}